Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,13 +29,17 @@ jobs:
     
     - name: Verify Rokit Installation
       run: |
-        ls -l $HOME/.rokit/bin  # List installed files for debugging
+        ls -l $HOME/.rokit/bin
         echo "Checking if Rokit is in PATH..."
         which rokit || echo "Rokit not found!"
         rokit --version
     
     - name: Install Selene
-      run: rokit install selene | bash
+      run: |
+        ls -l $HOME/.rokit/bin
+        echo "Checking if Rokit is in PATH..."
+        which rokit || echo "Rokit not found!"
+        rokit install selene
     
     - name: Lint
       run: |
